/**
 * Auctor Systems — 8 Agent Office Personas & Workstation Data
 * Represents the 8 specialized women and their artistic studio environments.
 */

export const AGENTS = [
  {
    id: 'planning',
    backendName: 'Planning',
    index: 0,
    name: 'Victoria Vance',
    role: 'Project Planning Specialist',
    stationTitle: 'Architectural Planning Desk',
    color: '#8B4513',
    accentColor: '#D89E3A',
    props: ['Blueprints', 'Drafting Ruler', 'Brass Compass', 'Milestone Scrolls'],
    description: 'Deconstructs user vision into site architecture, page hierarchies, and delivery milestones.',
    outfit: 'Tailored tweed vest, crisp ivory silk blouse, hair pinned with amber clip',
    deskItems: {
      left: 'Blueprint Tube & Rolled Maps',
      center: 'Large Drafting Table with Site Hierarchy Wire',
      right: 'Brass Desk Lamp & Steaming Tea',
    },
  },
  {
    id: 'requirements',
    backendName: 'Requirements',
    index: 1,
    name: 'Beatrice Stone',
    role: 'Systems Requirements Analyst',
    stationTitle: 'Requirements Analysis Studio',
    color: '#3D5A80',
    accentColor: '#98C1D9',
    props: ['Spec Pinboard', 'Wireframe Sketches', 'Sticky Matrix', 'Taxonomy Ledger'],
    description: 'Defines functional requirements, WCAG accessibility benchmarks, and responsive constraints.',
    outfit: 'Cashmere cardigan in forest green, tortoiseshell spectacles, linen trousers',
    deskItems: {
      left: 'Cork Pinboard with User Flow Nodes',
      center: 'Open Technical Ledger & Annotations',
      right: 'Categorized Sticky Color Matrix',
    },
  },
  {
    id: 'design',
    backendName: 'Design',
    index: 2,
    name: 'Clara Delacroix',
    role: 'UI/UX Design Architect',
    stationTitle: 'Atelier of Visual Systems',
    color: '#9C4146',
    accentColor: '#E29578',
    props: ['Color Swatch Wall', 'Typography Specimen Book', 'Ceramic Palette Tiles', 'Botanical Branch'],
    description: 'Engineers color tokens, Google Font pairings, responsive scales, and visual interaction states.',
    outfit: 'Minimalist charcoal apron over plum knitwear, sculptured brass rings',
    deskItems: {
      left: 'Pantone & HSL Tile Samples on Linen Mat',
      center: 'Digital Stylus Tablet with Component Hierarchy',
      right: 'Earthenware Vase with Dried Eucalyptus',
    },
  },
  {
    id: 'development',
    backendName: 'Development',
    index: 3,
    name: 'Maya Thorne',
    role: 'Senior Frontend Developer',
    stationTitle: 'Code Construction Suite',
    color: '#2A4365',
    accentColor: '#63B3ED',
    props: ['Dual High-Res Monitors', 'Mechanical Keyboard', 'Espresso Demitasse', 'Brass Anglepoise'],
    description: 'Crafts production HTML5, CSS custom properties, and vanilla JS interactions into real files.',
    outfit: 'Heavyweight black turtleneck, rolled cuffs, silver mechanical watch',
    deskItems: {
      left: 'Double Espresso on Stone Coaster',
      center: 'Dual Screens displaying Syntax-Highlighted Code',
      right: 'Custom Mechanical Keyboard with Wood Wrist Rest',
    },
  },
  {
    id: 'testing',
    backendName: 'Testing',
    index: 4,
    name: 'Astrid Lindqvist',
    role: 'QA & Accessibility Auditor',
    stationTitle: 'Quality & Audit Laboratory',
    color: '#316843',
    accentColor: '#68D391',
    props: ['Inspector Tablet', 'Contrast Color Gauge', 'Checklist Ledger', 'Green Certification Seal'],
    description: 'Audits HTML validity, responsive boundaries, color contrast ratios, and initiates code corrections.',
    outfit: 'Structured navy blazer, silver pendant, neatly parted blonde chignon',
    deskItems: {
      left: 'Accessibility Contrast Prism & Device Emulators',
      center: 'Lighthouse Audit Gauge & Severity Ledger',
      right: 'Wax Seal Stamp & Verified Green Ribbons',
    },
  },
  {
    id: 'documentation',
    backendName: 'Documentation',
    index: 5,
    name: 'Genevieve Ward',
    role: 'Technical Documentation Writer',
    stationTitle: 'Editorial Archive & Scribe',
    color: '#744210',
    accentColor: '#D69E2E',
    props: ['Bound Morocco Leather Journal', 'Fountain Pen', 'Antique Paperweight', 'Document Ribbons'],
    description: 'Authors README guides, architectural specifications, and setup instructions matching the codebase.',
    outfit: 'Cream wool sweater with ribbed collar, brass oval spectacles, burgundy velvet headband',
    deskItems: {
      left: 'Stack of Archival Heavyweight Papers',
      center: 'Vintage Scribe Table with Fountain Pen & Inkwell',
      right: 'Completed Bound README Documentation',
    },
  },
  {
    id: 'deployment',
    backendName: 'Deployment',
    index: 6,
    name: 'Nadia Chen',
    role: 'DevOps & Deployment Specialist',
    stationTitle: 'Infrastructure & Cloud Relay',
    color: '#4A5568',
    accentColor: '#A0AEC0',
    props: ['Server Telemetry Terminal', 'Fiber Patch Module', 'Vercel Config Console', 'Antenna Relay'],
    description: 'Configures production routing, vercel.json parameters, and orchestrates cloud deployment.',
    outfit: 'Utility work shirt in slate grey, lanyard with security fobs, hair in sleek high ponytail',
    deskItems: {
      left: 'Miniature Server Rack with Status Indicator LEDs',
      center: 'Multi-window Network Terminal showing DNS routes',
      right: 'Transmitter Antenna with Soft Amber Signal Pulse',
    },
  },
  {
    id: 'marketing',
    backendName: 'Marketing',
    index: 7,
    name: 'Sophia Laurent',
    role: 'Digital Marketing Strategist',
    stationTitle: 'Brand & Launch Pavilion',
    color: '#6B21A8',
    accentColor: '#D8B4FE',
    props: ['Campaign Moodboard', 'Vintage Chrome Ribbon Mic', 'Typography Headlines', 'Launch Calendar'],
    description: 'Synthesizes value propositions, SEO keyword matrices, social threads, and launch collateral.',
    outfit: 'Burgundy trench dress, silk neck scarf with geometric print, gold hoop earrings',
    deskItems: {
      left: 'Social Waveform Display & Viral Thread Blueprint',
      center: 'Story Magazine Mockup with Hero Photography',
      right: 'Brass Bell & Launch Countdown Clock',
    },
  },
];
